In [9]:
import numpy as np

#A,Bの多次元配列を格納
A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3],[4,5,6,7]])

#積の結果
print(np.dot(A,B))

#最大値
print(np.dot(A,B).max())


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
